version: 0.2

env:
  secrets-manager:
    Organization: prod/sonarqube:Organization
    HOST: prod/sonarqube:Host
    LOGIN: prod/sonarqube:SonarToken
    Project: prod/sonarqube:Project

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip sonar-scanner-cli-4.8.0.2856-linux.zip
      - mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
      - chmod -R 775 /opt/sonar-scanner
      - export PATH=$PATH:/opt/sonar-scanner/bin/
      - echo $PATH
      - echo "stage pre_build completed"
  build:
    commands:
      - echo $SONARQUBE_TOKEN
      - /opt/sonar-scanner/bin/sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization > sonarqube_scanreport.json
